name: SCA Scan w/ Tivy

on:
  workflow_run:
    workflows:
      - "Build Pipeline"
    types:
      - completed

jobs:
  sca:
    name: SCA Scan w/ Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'SCA-trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # - name: Upload Trivy output as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: SCA-trivy-results
      #     path: SCA-trivy-results.sarif
      

        
      

