name: CI + DevSecOps + Deploy ASP.NET Core to Azure

on:
  push:
    branches: [ main, master ]   # run on both main & master
  workflow_dispatch:             # allow manual trigger

env:
  AZURE_WEBAPP_NAME: rawsolutions   # must match your Azure Web App name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Upload Published Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: publish/

  security-scans:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Published Artifacts
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: publish/

      - name: Image Scan w/ Trivy
        run: trivy fs --exit-code 0 publish

      - name: SAST w/ SonarQube
        run: echo "Run SonarQube analysis here (sonar-scanner command)"

      - name: SCA w/ Trivy
        run: trivy config --exit-code 0 .

      - name: DAST w/ OWASP Zap
        run: echo "Run OWASP Zap scan here (adjust target URL)"

  deploy:
    runs-on: ubuntu-latest
    needs: [security-scans]
    steps:
      - name: Download Published Artifacts
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: publish/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPPUBLISHPROFILE }}
          package: ./publish
